#spring:
#  dubbo:
#    application:
#      name: duboo-consumer
#      id: duboo-consumer
#    registry:
#      address: 192.168.226.130             # zookeeper注册中心的地址
#      port: 2181                           # zookeeper注册中心的端口
#    consumer:
#      timeout: 1000
#      check: true                          # 服务启动时检查被调用服务是否可用
#      retries: 2                           # 服务调用重试次数