spring:
  dubbo:
    application:
      name: dubbo-service
      id: dubbo-service
    base-package: com.dubbo.service
    registry:
      address: 192.168.226.130                   # zookeeper注册中心的地址
      port: 2183                                 # zookeeper注册中心的端口
    protocol:
      name: dubbo
    provider:
        retries: 0                                 # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试
server:
  port: 18888

